name: Deploy to OCI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            cd /home/ubuntu/portfolio_backend
            git pull
            ./mvnw clean package -DskipTests
            cp target/*.jar /home/ubuntu/app.jar
            sudo systemctl restart portfolioapi
